### ISSUE TITLE
The Packer Attribute is unknown

### ISSUE THREAD

**Issue by ShoshanaTzi** [postsharp/PostSharp.Community.Packer#1]
Hi,
I installed the PostSharp.Comunity.Packer 1.1.0 successfully
(and also PostSharp 6.6.7 with full license)
Compile succeeded.
But when I added the `[assembly: Packer] `
I got an error: `The type or namespace name 'PackerAttribute' could not be found (are you missing a using directive or an assembly reference?)`

In the intellisence of PostSharp.Comunity.Packer I see only Templates:
![image](https://user-images.githubusercontent.com/24288859/100534728-bb6db600-321a-11eb-9734-47b8954b8451.png)

What I missed?

**Comment by Soothsilver** [comment]
What you're doing should work.

What happens if you add `[assembly: PostSharp.Community.Packer.Packer]` to your code? Does it complain that the type doesn't exist? If yes, could you attach your project or a minimal example? Merely installing the package in a project and adding this attribute works for me.

**Comment by ShoshanaTzi** [comment]
Thanks for your quick response.
Yes, I just added the `[assembly: PostSharp.Community.Packer.Packer]`  and got the error above.
I attach the csproj file (as txt), anything more?
[1.txt](https://github.com/postsharp/PostSharp.Community.Packer/files/5613920/1.txt)

**Comment by Soothsilver** [comment]
Thank you.

This is caused by the fact that your project targets .NET Framework 4.0, but the DLL in Packer is targeted at .NET Standard 2.0. 

If you can change the target framework of your project to .NET Framework 4.7.2, that will resolve the issue.

If not, you would need to recompile the Packer binary with .NET 4.0 as the target framework. I think it's doable, but I didn't try. If you make a pull request on it, I'll merge it in and republish.

**Comment by ShoshanaTzi** [comment]
Hi,
Thanks
I didn't notice the .net standard 2.0 depenecy
I will try to upgrade

‫בתאריך יום ב׳, 30 בנוב׳ 2020 ב-11:31 מאת ‪Petr Hudeček‬‏ <‪
notifications@github.com‬‏>:‬
