### ISSUE TITLE
License key required?

### ISSUE THREAD

**Issue by chrisbbe** [postsharp/PostSharp.Community.Packer#2]
During compilation, the NuGet package complains about no valid license key been installed. Browsing the website postsharp.net does not lead me to any page or form to subscribe for a free license, besides that, the website states _"No key required for community and trial."_ So is this package lagging behind changes in the license policy for PostSharp?

**Comment by gfraiteur** [comment]
The expected behavior is that a dialog box would open, asking you to enable PostSharp Community. If this does not happen for some reason, you can install PostSharp Tools for Visual Studio (and uninstall it immediately if you don't like it),  or execute a file that would be typically named `C:\ProgramData\PostSharp\6.8.3\bin.Release\net472\UserInterface\PostSharp.Settings.UI.exe` with the proper version number.
